name: CivEnchant
main: com.gmail.sharpcastle33.CivEnchant
version: 1.0
commands:
   givecivenchant:
      description: (OP ONLY) debug command for setting an enchant on an item
      usage: with an item in main hand /gce <enchant> <level>
      alias: gce